### ISSUE TITLE
Assessment biomass trends for diagnostics

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/neus-atlantis#14]
There may not be assessments for all of these that are any different from survey time series; if so please make a note of assessment type and record the source. 

- [x] Start a wiki page or rmd for documentation of assessment sources

Place original pdf in folder [Stock Assessment Reports](https://drive.google.com/open?id=1rfq9IPBKPt5xquTsZLnx9lIrXXiS_m1X) on EDAB google drive

- [x] Atlantic cod
- [x] Atlantic herring
- [x] Atlantic mackerel
- [x] Atlantic salmon
- [x] Atlantic surf clam
- [ ] Blue crab (State Managed)
- [x] Butterfish
- [x] Goosefish
- [x] Haddock
- [x] Illex squid
- [x] Little skate
- [ ] Lobster (State Managed)
- [x] Loligo squid (Doryteuthis)
- [ ] Menhaden (State Managed)
- [x] Ocean quahog
- [x] Pollock
- [x] Sea scallop
- [x] Silver hake
- [x] Spiny dogfish
- [x] Summer flounder
- [x] Winter flounder
- [x] Winter skate
- [x] Yellowtail flounder

Double check calcs before getting these:
- [x] Acadian redfish
- [ ] Weakfish (State Managed)
- [x] Smooth dogfish

**Comment by gambler1650** [comment]
- [ ] Get the information needed for the first three species (Atlantic cod, Atlantic herring, Atlantic mackerel)

**Comment by andybeet** [comment]
@sgaichas @slarge @gambler1650 @RMORSEcode 

Rather than creating a new repo for the pdfs/extracted data etc. within this repo, should we create a "docs" folder for the pdfs, a "data-raw" folder for the code to extract tables/massage data, and a "data" folder for the product?

Or is it best to keep all of this separate?

**Comment by sgaichas** [comment]
My suggestion is not to use a "docs" folder in this repo only because 
this is where gh-pages will be hosted so it might get confusing.

I think extracting assessment outputs is a general enough need that it 
can be in its own repo. We will also use it for the SOE for example, and 
possibly to compare with other models.

I'm not sure if pdfs play well with github? However, a repo that has R 
code to extract assessment data from pdfs and other sources (posted ADMB 
.rep files for groundfish assessments) would be really handy. The pdfs 
themselves could live on google drive and the R code could look there.

**Comment by andybeet** [comment]
new repo created:

https://github.com/NOAA-EDAB/assessmentData

The data extractions are in RDS files found in the data folder. 
The reports that the data are extracted from can be found in docs folder. 
The code can be found in R folder.  
Data info in vignettes folder.
Lets discuss at meeting

**Comment by andybeet** [comment]
@sgaichas Change of plan.
We are using comlandr and Survdat to obtain biomass and landing time series for model diagnostics and calibration since some assessments don't have the info we need and some are have multiple stocks managed separately. We will use some of the assessments (as a check) to see how true the data pulls are

**Comment by sgaichas** [comment]
That makes sense. I would just double check that NEFSC survey time series are not at odds with assessment trends (Atlantic mackerel comes to mind) and use the assessments trend as the default if they are.

**Comment by andybeet** [comment]
We have many of the species data from stock assessments thanks to [Stock SMART](https://www.st.nmfs.noaa.gov/stocksmart/?app=homepage). However only species actively managed as part of a federal FMP are included.

This leaves 
* Weakfish (ASMFC)
* Am. lobster (ASMFC)
* Blue crab (Chesapeake Bay)
* Menhaden (ASMFC)

Will use most recent stock assessments from the ASMFC and Chesapeake Bay SAC to obtain data.

Unsure on ***Loligo squid (Doryteuthis)***
I only see these records in our cfdbs
1. SQUID,UNC         
2. SQUID (LOLIGO)    
3. SQUID (ILLEX)     
4. SQUIDS,LOLIGINIDAE

**Comment by sgaichas** [comment]
That sounds great @andybeet, thanks for looking into this.

For the squid formerly known as Loligo, I'd suggest pulling catch from the assessment document to avoid problems with interpreting the unc and loliginidae categories. This would treat it consistently with the other species where we use most recent assessments.

We just reviewed the longfin squid management track assessment last week ([summary](https://apps-nefsc.fisheries.noaa.gov/saw/sasi/uploads/2020_DORY_UNIT_RPT_.pdf)) and the data is at the portal ([this should link to a zipped Longfin squid file if it works](https://apps-nefsc.fisheries.noaa.gov/saw/sasi/uploads/2020_DOR_UNIT_70374.zip))

**Comment by andybeet** [comment]
I didn't realize Loligo is no more. And i also wasn't sure of the name (Doryteuthis) since i haven't see that species in any catch data. Looking online they are both longfin inshore squid but didnt know what the difference was and or what was meant by including this species.

However the Stock SMART data includes stock assessment data for Lologo pealeii. Is this what we want?

**Comment by sgaichas** [comment]
Probably--that is the old name but we should double check to make sure it matches what is in Lisa's assessment. 
I'm surprised it isn't listed under the new scientific name, but many in the fishery still refer to it as Loligo too. I think it was a recent change. I can't keep up with taxonomy...
http://www.marinespecies.org/aphia.php?p=taxdetails&id=410354

**Comment by andybeet** [comment]
Chatted To Lisa. Loligo pealeii and (Doryteuthis (Amerigo) pealeii ARE the same species. The name changed in 2009 however the species is still coded as Loligo pealeii in the commercial fisheries database

**Comment by andybeet** [comment]
Stock SMART  and the [`stocksmart`](https://github.com/NOAA-EDAB/stocksmart) R packages resolves most of these issues
