### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/neus-atlantis#18]
I suggest that before we get too far down the road, it might be a good idea to modify the repo name (and all associated files) to a standard convention. 

I suggest something like:
neus_atlantis (I like underscores, but I think some languages might have issues) or
neus-atlantis

**Comment by gambler1650** [comment]
Changed.  And apparently even though the link names in the wiki and other places haven't actually changed, they point to the right place (clicking on a link that has the underlying name atlantis-RM leads to the updated name)

Scott, did you also want all the parameter names and such also changed to this convention, or were you referring mainly to the name and the links within the wiki and issues?

**Comment by slarge** [comment]
Thanks, Rob. I suggest we work to be as consistent as possible while still being pragmatic. I'm not exactly sure what parameter names you are referring to.

**Comment by gambler1650** [comment]
Sorry, I meant 'parameter file names'.
